

spring.datasource.url=jdbc:postgresql://db:5432/giangdb
spring.datasource.username=gianguser
spring.datasource.password=giangpass
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway config
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.redis.time-to-live=60000 # 60 seconds
